version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - checkout
      - run: risk_pd_model
          name: create_dir
          command: |
            ls
#            mkdir /home/circleci/risk_pd_model
#            mv * /home/circleci/risk_pd_model
            pwd
#            for i in $list; do
#              mv $i risk_pd_model/
#            done

#      - sonarcloud/scan
      - persist_to_workspace:
          root: /home/circleci/risk_pd_model
          paths:
            - .
  testing:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:

      - attach_workspace:
          at: /home/circleci/risk_pd_model

      - run:
          name: check_files
          command: |
            ls -la
            pwd

workflows:
  main:
    jobs:
      - build

      - testing:
          requires:
            - build
