version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build
