version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - checkout
      - sonarcloud/scan
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - .
  testing:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - attach_workspace:
          at: /tmp/workspace

workflows:
  main:
    jobs:
      - build

      - testing
