version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - checkout
      - run:
          name: createe_dir
          command: |
            ls > list.txt
            mkdir risk_pd_model
            pwd
            for i in $list.txt; do
              mv $i risk_pd_model/
            done

#      - sonarcloud/scan
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .
  testing:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: check_files
          command: |
            ls -la
            pwd

workflows:
  main:
    jobs:
      - build

      - testing:
          requires:
            - build
