version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
      - image: 'circleci/python:3.7.1'

    steps:
      - checkout
      - run:
          name: check_files
          command: |
            pwd
            mkdir risk_pd_model
            ls -la
#      - sonarcloud/scan
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - risk_pd_model
  testing:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:

      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: check_files
          command: |
            ls -la risk_pd_model
            pwd

workflows:
  main:
    jobs:
      - build

      - testing:
          requires:
            - build
